### ISSUE TITLE
Python required to use the plugins ?

### ISSUE THREAD

**Issue by chrizilla** [flashdagger/ytdlp-plugins#1]
I am on Windows and have yt-dlp.exe but don't have Python.
I assume, I cannot use your ServusTV and auf1 plugins in this case ?

**Comment by flashdagger** [comment]
No. Since it is using dynamic patching, it needs the python packages.

**Comment by flashdagger** [comment]
Videos from auf1.tv you can still download with pure yt-dlp by right-clicking on the video and chosing "Copy the video URL", since the videos are actually Peertube hosted.

**Comment by chrizilla** [comment]
That's what I thouht, thanks for the confirmation. I will dive into Python then.

Why can't pure yt-dlp download from auf1.tv then with yt-dlp's peertube extractor – or even with the generic extractor, given that the video link seems readily available on the website ?

**Comment by flashdagger** [comment]
> Why can't pure yt-dlp download from auf1.tv then with yt-dlp's peertube extractor – or even with the generic extractor, given that the video link seems readily available on the website ?

Because the video links are hidden in some JS code. The generic extractor is not capable to find them.

**Comment by chrizilla** [comment]
thanks. and the yt-dlp peertube extractor ?

**Comment by flashdagger** [comment]
It works like this:
- every extractor supports only URLs that matches its own pattern
- some sites provide video links under a different URL, hidden somewhere in the HTML, JS
- for those sites you need an extractor that can find the links and forwards them to another extractor

E.g. `yt-dlp https://twitter.com/YouTube/status/1479498063949570051 -F` finds a YouTube video embedded in a twitter post.

**Comment by chrizilla** [comment]
Thanks. So in this case yt-dlp doesn't find the video, because there is no auf1 extractor (capable of finding the peertube link) and the generic extractor apparently doesn't find the peertube link, is this correct ?

I guess, if I want to download with yt-dlp, I would have to find the peertube link manually in the html and then feed the peertube link to yt-dlp, so that yt-dlp's peertube extractor handles it, right ?

**Comment by flashdagger** [comment]
Exactly. As I write, you get the PeerTube link by right-clicking on the video in the browser and choosing "Copy the video URL".

**Comment by chrizilla** [comment]
thanks so much for explaining all that to me. cheers
