### ISSUE TITLE
auf1 is broken

### ISSUE THREAD

**Issue by BergbauerSepp** [flashdagger/ytdlp-plugins#3]
Linux xxxxxxxxxx 5.18.0-0.bpo.1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1~bpo11+1 (2022-06-14) x86_64 GNU/Linux

ytdlp-plugins -v
[debug] Command-line config: ['-v']
[debug] Loaded 3 plugins which are not part of yt-dlp. Use at your own risk.
[debug]  [auf1]            via 'ytdlp_plugins.extractor.auf1.Auf1IE'             (v2022.05.06)
[debug]  [servustv:search] via 'ytdlp_plugins.extractor.servustv.ServusSearchIE' (v2022.07.17)
[debug]  [servustv]        via 'ytdlp_plugins.extractor.servustv.ServusTVIE'     (v2022.07.17)
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.18.0-0.bpo.1-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1673 extractors

Usage: ytdlp-plugins [OPTIONS] URL [URL...]

ytdlp-plugins: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

ytdlp-plugins https://auf1.tv/nachrichten-auf1/nachrichten-auf1-vom-15-september-2022/
[auf1] nachrichten-auf1-vom-15-september-2022: Downloading JSON metadata
WARNING: [auf1] nachrichten-auf1-vom-15-september-2022: Unsupported URL: https://auf1.tv/nachrichten-auf1/nachrichten-auf1-vom-15-september-2022/
[auf1] nachrichten-auf1-vom-15-september-2022: Downloading webpage
[auf1] nachrichten-auf1-vom-15-september-2022: Downloading payload.js
ERROR: [auf1] nachrichten-auf1-vom-15-september-2022: Unable to extract payloadjs

**Comment by flashdagger** [comment]
Thx for the issue. I already noticed it myself. But might need some time to fix it because I'm busy at the moment.
So patches are welcome. Nevertheless happy to see there is a demand for the plugin :)

Temporary Workaround:
Right-click on the video and select "Copy the video URL". The videos are hosted on _gegenstimme.tv_ which is supported by yt-dlp's generic extractor.

**Comment by flashdagger** [comment]
[New release available](https://pypi.org/project/ytdlp-auf1/2022.9.16/)

**Comment by BergbauerSepp** [comment]
Big thanks for solving this problem so fast!!!
pip install ytdlp-auf1==2022.9.16
Works great!

Thanks!
