### ISSUE TITLE
How to use plugin when using in python not using by command line

### ISSUE THREAD

**Issue by demon071** [flashdagger/ytdlp-plugins#4]
Hi, I want how to use the plugin with yt-dlp, can you give me instructions?

**Comment by flashdagger** [comment]
Sure. But please be more specific. Also give an example how you are using yt-dlp.

**Comment by demon071** [comment]
i'm trying to add the plugin to yt-dlp, but it seems to only be able to run the plugin when it's in the same directory as the source code. When I install yt-dlp from pip and create ytdlp_plugin folder in my project folder but it doesn't work

**Comment by flashdagger** [comment]
So you have project folder with your source code.

Do you want to
A) use an existing plugin installed with pip in [embedded yt-dlp](https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp) code
or
B) develop your own plugin under `ytdlp_plugins/extractor/<plugin>.py`

Please be as specific as possible by describing your expectation.

**Comment by demon071** [comment]
I want use an existing plugin installed with pip in [embedded yt-dlp](https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp) code
