### ISSUE TITLE
missing formats due to AUF1 API change

### ISSUE THREAD

**Issue by BergbauerSepp** [flashdagger/ytdlp-plugins#8]
last successful download 13.dez.2023

hey, They changed their API again 😒

```
Linux xxxxxxxxxx 5.15.131-1-pve #1 SMP PVE 5.15.131-2 (2023-11-14T11:32Z) x86_64 GNU/Linux

yt-dlp -v https://auf1.tv/das-grosse-interview/alice-weidel-in-deutschland-wird-politik-gegen-das-deutsche-volk-gemacht
[debug] Command-line config: ['-v', 'https://auf1.tv/das-grosse-interview/alice-weidel-in-deutschland-wird-politik-gegen-das-deutsche-volk-gemacht']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.15.131-1-pve-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.34.1, urllib3-2.1.0, websockets-10.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Extractor Plugins: Auf1IE, Auf1RadioIE, PmWissenIE, PmWissenSearchIE, ServusSearchIE, ServusTVIE
[debug] Plugin directories: ['/usr/local/lib/python3.9/dist-packages/yt_dlp_plugins']
[debug] Loaded 1907 extractors
[auf1] Extracting URL: https://auf1.tv/das-grosse-interview/alice-weidel-in-deutschland-wird-politik-gegen-das-deutsche-volk-gemacht
[auf1] alice-weidel-in-deutschland-wird-politik-gegen-das-deutsche-volk-gemacht: Downloading JSON metadata
ERROR: [auf1] alice-weidel-in-deutschland-wird-politik-gegen-das-deutsche-volk-gemacht: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 2751, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1076, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [auf1] alice-weidel-in-deutschland-wird-politik-gegen-das-deutsche-volk-gemacht: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by flashdagger** [comment]
Apparently the download links were migrated to a different hoster.
Please try the currently updated plugin [version 2023.12.18](https://pypi.org/project/ytdlp-auf1/2023.12.18/).

**Comment by BergbauerSepp** [comment]
**BIG **Thanks!****
It works again :)
I hope it wasn't too much work.


Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
root@XXXXXXXXXX:~# yt-dlp -Uv https://auf1.tv/nachrichten-auf1/berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel 
[debug] Command-line config: ['-Uv', 'https://auf1.tv/nachrichten-auf1/berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.11-7-pve-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.1.0, websockets-11.0.3, xattr-0.9.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Extractor Plugins: Auf1IE, Auf1RadioIE, DTubePluginIE, DTubeQueryPluginIE, DTubeSearchPluginIE, DTubeUserPluginIE, PmWissenIE, PmWissenSearchIE, ServusSearchIE, ServusTVIE
[debug] Plugin directories: ['/usr/local/lib/python3.10/dist-packages/yt_dlp_plugins']
[debug] Loaded 1911 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[auf1] Extracting URL: https://auf1.tv/nachrichten-auf1/berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel
[auf1] berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel: Downloading _payload.json
[auf1] berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel: Downloading 1 format(s): 5000
[debug] Invoking hlsnative downloader on "https://vz-0b49e78d-475.b-cdn.net/c1c0870a-b6e5-420e-bea7-c73cf1d94c85/1920x1080/video.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 38
[download] Destination: Berliner Kommentar： Politisch motiviert？ Plagiats-Vorwürfe gegen Alice Weidel [berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel].mp4
[download] 100% of  101.81MiB in 00:00:01 at 62.21MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Berliner Kommentar： Politisch motiviert？ Plagiats-Vorwürfe gegen Alice Weidel [berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel].mp4'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Berliner Kommentar： Politisch motiviert？ Plagiats-Vorwürfe gegen Alice Weidel [berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Berliner Kommentar： Politisch motiviert？ Plagiats-Vorwürfe gegen Alice Weidel [berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Berliner Kommentar： Politisch motiviert？ Plagiats-Vorwürfe gegen Alice Weidel [berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Berliner Kommentar： Politisch motiviert？ Plagiats-Vorwürfe gegen Alice Weidel [berliner-kommentar-politisch-motiviert-plagiats-vorwuerfe-gegen-alice-weidel].temp.mp4'
