### ISSUE TITLE
Add "createdAt":"2023-11-02T22:35:11.920Z" from html fetch to `-J`

### ISSUE THREAD

**Issue by zackees** [flashdagger/ytdlp-plugins#9]
This field exists in the brighteon html fetch.

This is a feature request to include this in the info.json dump

**Comment by zackees** [comment]
Sorry i'm dumb, the plugin wasn't installed

**Comment by flashdagger** [comment]
```yt-dlp https://www.brighteon.com/<video_id> --print "%(timestamp>%Y-%m-%dT%H:%M:%SZ)s"```
will give you a similar format. But note that timestamp is rounded to seconds.
